### ISSUE TITLE
app加固后crash

### ISSUE THREAD

**Issue by LeoonZHANG** [BATTZION/AutoReinforce#2]
配置文件
[Application]
app = drozer.apk
num = 0
[FUNCTION0]
class =
function =
signature =
运行成功并生成签名的apk文件
但是在android 4.4真机上运行直接crash
logcat:
07-25 16:10:10.251 17772-17772/com.mwr.dz A/libc: Fatal signal 11 (SIGSEGV) at 0x793ae124 (code=2), thread 17772 (com.mwr.dz)
07-25 16:10:10.281 5144-5144/? E/ActivityThread: Activity com.htc.launcher.Launcher has leaked IntentReceiver com.htc.launcher.masthead.FeedActionBar$2@41f06a08 that was originally registered here. Are you missing a call to unregisterReceiver()?
    android.app.IntentReceiverLeaked: Activity com.htc.launcher.Launcher has leaked IntentReceiver com.htc.launcher.masthead.FeedActionBar$2@41f06a08 that was originally registered here. Are you missing a call to unregisterReceiver()?
        at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:895)
        at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:664)
        at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1670)
        at android.app.ContextImpl.registerReceiver(ContextImpl.java:1650)
        at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:481)
        at com.htc.launcher.masthead.FeedActionBar.<init>(FeedActionBar.java:92)
        at com.htc.launcher.masthead.FeedActionBar.<init>(FeedActionBar.java:81)
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at android.view.LayoutInflater.createView(LayoutInflater.java:594)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:839)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:745)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:375)
        at android.app.Activity.setContentView(Activity.java:1997)
        at com.htc.launcher.Launcher.onCreate(Launcher.java:1139)
        at android.app.Activity.performCreate(Activity.java:5312)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2552)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2653)
        at android.app.ActivityThread.access$800(ActivityThread.java:156)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5872)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1069)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)
        at dalvik.system.NativeStart.main(Native Method)
07-25 16:10:10.581 4829-17786/? E/ActivityManager: App crashed! Process: com.mwr.dz

**Comment by xdek42** [comment]
页权限配置问题，已修复
